encoding: UTF-8
title: StandWithUkraine
description: "Russia invaded Ukraine, killing tens of thousands of civilians and displacing millions more. It's a genocide. Please help us defend freedom, democracy and Ukraine's right to exist."
domain: denisoster.github.io
baseurl: ""
url: https://oster.page
social_sharing: true
markdown: GFM
repository: denisoster/denisoster.github.io

readme_index:
  enabled:          true
  remove_originals: true
  with_frontmatter: false

plugins:
  - jekyll-sitemap
